
LIST_INIT_PACKET_LENGTH = 64
LIST_FILE_PACKET_LENGTH = 1024
GEN_PACKET_LENGTH = 4096

HOST_PORT = 7878


DOWNLOAD_CMDS = ["download", "dl"]
LIST_CMDS = ["list", "ls"]
UPLOAD_CMDS = ["upload", "up"]
EXIT_CMDS = ["exit", "quit", "q"]
LISTEN_PORT = 7900


INVALID_FILE_UPLOAD = "File not found"
